#pragma once

#define KLD_MOUSE_BUTTON_1 0
#define KLD_MOUSE_BUTTON_2 1
#define KLD_MOUSE_BUTTON_3 2
#define KLD_MOUSE_BUTTON_4 3
#define KLD_MOUSE_BUTTON_5 4
#define KLD_MOUSE_BUTTON_6 5
#define KLD_MOUSE_BUTTON_7 6
#define KLD_MOUSE_BUTTON_8 7
#define KLD_MOUSE_BUTTON_LAST KLD_MOUSE_BUTTON_8
#define KLD_MOUSE_BUTTON_LEFT KLD_MOUSE_BUTTON_1
#define KLD_MOUSE_BUTTON_RIGHT KLD_MOUSE_BUTTON_2
#define KLD_MOUSE_BUTTON_MIDDLE KLD_MOUSE_BUTTON_3